#!/bin/bash
set -euxo pipefail

cp -r /mnt /work
cd /work

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install --no-install-recommends build-essential devscripts equivs lsb-release
mk-build-deps -i --tool 'apt-get --no-install-recommends -y'

VISUAL=touch dch --local "~deb$(lsb_release -rs | cut -d . -f 1)u"
debuild -us -uc -sa

shopt -s nullglob
install -o "$DIST_UID" -g "$DIST_GID" -m 644 ../{*.changes,*.deb,*.dsc,*.tar.*,*.buildinfo} /mnt/dist/
