#!/bin/bash
set -euxo pipefail
cd /mnt

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install --no-install-recommends build-essential devscripts equivs
mk-build-deps -i --tool 'apt-get --no-install-recommends -y'
debuild -us -uc -sa
mv ../{*.changes,*.deb,*.dsc,*.tar.*} dist/
